### ISSUE TITLE
Cleansing / Annotation - Finished 상태에 대한 정의

### ISSUE THREAD

**Issue by bongwon7** [Digital-Maritime-Consultancy/VoTT-dot-server#10]
아래 URL에 따른 Annotation-Finished 상태일때 저장된 어노테이션 정보를 불러오지 않습니다.

22. 2. 21 정진기) Finished status는 VoTT가 어떻게 이를 표출/기능해야할지 협의된 적이 없습니다.
22. 2. 22 정봉원)
메일 드린 내용 - Stella 에서 설정 문제로 불러오기 안된것이므로 정정합니다.

Cleansing In-progress 상태, Review 상태, Finished 상태: 현재와 같이 isDisabled상태가 보여지면 되므로 이부분은 수정 불필요합니다.
Annotation In-progress 상태인 경우, Review 상태인 경우 - 어노테이션 정보 재로드 확인함
**Annotation Finished 상태 <- 미정의 어노테이션 결과를 뷰할수 있으면 좋겠습니다.**

**Comment by JinkiJung** [comment]
> **Annotation Finished 상태 <- 미정의 어노테이션 결과를 뷰할수 있으면 좋겠습니다.**

'미정'의 의미는 어떤 것인가요?
'뷰'의 의미는 사진과 어노테이션의 결과가 모두 표출되지만 수정이 불가하고 툴바도 표출되지 않는 것을 의미하시는지 확인하고자 합니다.

**Comment by bongwon7** [comment]
'미정의', 정의되지 않음 입니다.^^;
뷰의 의미는 작성 주신것 처럼 어노테이션 결과가 표출되지만 수정 불가, 툴바표출 X 의미가 맞습니다

**Comment by JinkiJung** [comment]
현재 편집 과정 중 미정의 어노테이션은 저장되지 않으며 만약 존재하는 경우 경고창이 뜨며 저장이 거절됩니다.
우선 말씀주신대로 어노테이션이 표출되는 것 기준으로 구현해보도록 하겠습니다.

**Comment by JinkiJung** [comment]
구현되어 반영되었습니다. 외부 라이브러리인 canvas editor에서의 도형 수정 이벤트를 막을 수 없기에 Finished에서도 어노테이션 수정 및 이동이 가능하지만 해당 수정이 DB에 반영되진 않습니다. 새로고침하면 원래대로 돌아오는 것을 보실 수 있을 겁니다. 
https://github.com/Digital-Maritime-Consultancy/VoTT-dot/pull/11

**Comment by bongwon7** [comment]
정상동작 확인했습니다. 감사합니다^^
