### ISSUE TITLE
안녕하세요^^

### ISSUE THREAD

**Issue by bongwon7** [Digital-Maritime-Consultancy/VoTT-dot-server#2]
이슈를 남겨봅니다~ 혹시 여기 남기는 게 괜찮으면 메일 대신 여기 기록해도 좋을것 같아요 :ㅇ)

**Comment by JinkiJung** [comment]
아주 좋습니다. :0)

**Comment by bongwon7** [comment]
메일 잘 받았습니다. 우선은 해당 문제가 되는 부분 TEXT 타입으로 변경하여 서버에 잘 저장됨을 확인한 상태입니다. :)
제 PC에서 잘 구동 안되는 것은 제 Springboot에서 jsonb관련 데이터 타입 인식 문제가 있는듯 합니다.
![image](https://user-images.githubusercontent.com/56225430/149851465-31d5dac4-85fd-4d6d-ad46-1ee504ade737.png)
그 외에는 정보가 vott-dot-server로 입수 되는데 별 문제가 없을 것으로 생각합니다.

감사합니다.
