### ISSUE TITLE
File.java isEnabled 관련 문의사항

### ISSUE THREAD

**Issue by bongwon7** [Digital-Maritime-Consultancy/VoTT-dot-server#4]
문의1)
안녕하세요? 다름이 아니라 지난번 협의때 File 구조체에 isEnabled로 안내드렸었는데요,
저희 시스템코드를 다시 보니 isDisabled네요. 혹시 변경 가능할까요? 번거롭게 해드려 죄송해요~

그리고 웹개발에서 boolean(primitive)타입을 쓰면 null처리가 되지 않아서
boolean -> Boolean 변수 정의로 하시면 좋을 듯 합니다.

(변경전)
private boolean isEnabled;
(변경후) 
private Boolean isDisabled;

isDisabled의 용례
NULL인 경우: 정제되지 않음
TRUE인 경우: 비활성화 됨
FALSE인 경우: 활성화 되어 가공의 대상 이미지가 됨.

문의2)
VoTT-dot server에 File.java에 fileName이 실제 파일 명이라면 똑같은 파일명이 있을때 문제가 될것 같은데요,
UUID, 또는 데이터베이스에 ID로 해서 findById 또는 findByUuid이런 쿼리를 해야 하지 않을까요?

**Comment by bongwon7** [comment]
아 문의 2는 취소할게요 uuid가 있네요.. 모델에는 드러나지 않지만 PostgreSQL DB처리하는 과정에서 돌려주나보네요^^;

**Comment by JinkiJung** [comment]
문의1은 연결된 pull request와 같이 구현되었습니다.

문의2는 관련 클래스들이 상속받는 Resource 클래스에 정의되어 있습니다.

우선 본 이슈는 닫도록 하겠습니다. 혹시 말씀주신 Boolean이 java.lang.Boolean 형식이 아니라면 커멘트 달아주세요. :0)
