### ISSUE TITLE
Connection information shall set system admin in first time.

### ISSUE THREAD

**Issue by bongwon7** [Digital-Maritime-Consultancy/VoTT-dot-server#6]
안녕하세요. VoTT에서 제가 처음에 1PC에서 connection 세팅을 하였는데, 다른 PC에 세팅하니 설정이 유지가 되지 않습니다.
아마도 웹소켓에서 서로 다른 연결로 인식하는 듯 합니다. 

ws://localhost:3000/sockjs-node/613/5vg3g5di/websocket

그러다 보니 서로 다른 PC의 연결마다의 connection setting이 필요합니다.

관리자가 한번 설정하면 이후 연결은 해당 설정이 적용되면 좋겠습니다^^

**Comment by JinkiJung** [comment]
말씀주신 부분은 해당 서버 주소를 VoTT-dot의 코드 혹은 설정에 고정값으로 지정하는 방법 외에는 해결이 어려워 보입니다.
이 방식으로 진행해야 할까요?

**Comment by bongwon7** [comment]
관리자가 특정 url 통해 connection 세팅 페이지로 이동하게 한 후에 연결 설정을 가능하도록 하고, 이후 websocket 생성과정에서는 저장된 설정값을 불러오도록 해야 할듯한데요. 고정값으로 하는것은 저도 추천드리고 싶지 않습니다^^; 

다만, 현재는 다른 PC에서 접속할때마다 초기 연결 세팅이 필요하다는 점 알아주셨으면 좋겠습니다~

**Comment by bongwon7** [comment]
그 한가지만 문의드리면, connection 세팅하는 부분은 관리자가 어쨋든 해야하는 부분일까요? 
아니면 Stella에서 보내드리는 정보로 세팅가능할까요? 

어느쪽이 더 괜찮으신지요?

**Comment by JinkiJung** [comment]
> 안녕하세요. VoTT에서 제가 처음에 1PC에서 connection 세팅을 하였는데, 다른 PC에 세팅하니 설정이 유지가 되지 않습니다. 아마도 웹소켓에서 서로 다른 연결로 인식하는 듯 합니다.
> 
> ws://localhost:3000/sockjs-node/613/5vg3g5di/websocket
> 
> 그러다 보니 서로 다른 PC의 연결마다의 connection setting이 필요합니다.
> 
> 관리자가 한번 설정하면 이후 연결은 해당 설정이 적용되면 좋겠습니다^^

말씀주신대로 클라이언트마다 Connection을 새로 생성하고 등록해야 함이 확인되었습니다. 

VoTT가 내부 메모리에 자체적으로 provider registry를 운용하기에 발생하는 문제로 파악됩니다.

해당 문제는 프로젝트 생성을 위한 Task JSON 값 중 connection 관련 정보를 취해 직접 생성하는 방법인데 이는 한 번 시도해볼만 합니다.

만약 이게 구현된다면 관리자가 설정할 필요가 없어집니다. 우선 한 번 구현을 시도해보고 다시 댓글 남겨 보겠습니다.

**Comment by JinkiJung** [comment]
결론이 났습니다. Stella에서 Task 생성 페이지로 넘어갈 때 해당 페이지에서 접근 가능한 값은 task ID외에는 없으며 해당 task를 생성하기 위한 API를 호출할 서버 url 또한 없습니다. 따라서 관리자가 이를 미리 등록해야 하는 단계를 두었던 것입니다.
해결책은 세 가지 중 하나로 보입니다.

- Task 생성 페이지로 이동 시 서버 url도 path parameter로 함께 전송 (바람직하진 않은 방법입니다.)
- VoTT-dot 코드 컴파일 시 고정값으로 제공 (Back to Stella 링크도 Task 프로젝트 생성 전 까지는 같은 방법으로 링크를 제공합니다.)
- 관리자가 API 서버 등록, 프로젝트 생성을 직접 수행하여 다수의 Task 프로젝트 한 번에 생성, 사용자는 생성 없이 바로 작업 화면으로 이동 (관리 로드 - 사용자 링크 제공의 타협점으로 보입니다.)

이 중 하나로 결정해주시면 구현에 반영하도록 하겠습니다.

**Comment by bongwon7** [comment]
세번째 시나리오가 잘 이해가 되지 않았습니다^^

관리자가 VoTT 설정 화면에서 Stella URL을 등록하고 나면
이후 생성되는 Task(VoTT의 프로젝트) 는 별도의 설정작업 없이 바로 작업화면으로 이동
서로 다른 PC에서 Connection 하더라도 관리자가 설정한 connection 설정 기반으로 생성

이게 가능한 시나리오인가요?

**Comment by JinkiJung** [comment]
맞습니다. 쉽게 말씀드리면 기존의 프로젝트 생성은 그대로 가져가되 관리자가 해당 작업을 일괄 수행하는 것입니다.
현재도 스텔라에 저장된 task 정보를 기반으로 개별 프로젝트를 생성시킬 때 해당 프로젝트를 위한 connection을 생성하여 설정합니다.
하지만 이 모든 생성 프로세스의 가장 처음 단계에서 task 생성을 요청할 API url(connection)이 요구되는 제약사항이 있는 것입니다.

**Comment by JinkiJung** [comment]
어쩌면 유동성을 배제하고 VoTT-dot에 Stella API를 연결시키는 개념으로 보면 고정값(혹은 설정값)으로 두는 것도 가능하겠네요.

**Comment by bongwon7** [comment]
![image](https://user-images.githubusercontent.com/56225430/155125918-af601d4b-64f6-46ed-ac9f-6e19511bc259.png)

http://localhost:3000/#/connections

네 이 화면에서 최초 Stella-url 과 인식서버 URL을 세팅해주고 나면 이후 생기는 모든 세션들은 저장된 값 기반으로 연결설정이 되게 하는게 어떨까 싶어서요.

그러면 데이터 TaskDto에서 Stella URL 등등도 다 불필요해질 듯 합니다.

다만 Stella에서 VoTT 에 대한 주소를 지정했을때 VoTT에서는 해당 연결 설정으로 이동하는 URL만 회신주실 수 있으면 자연스러울듯해서요.

**Comment by JinkiJung** [comment]
보여주신 connections 화면이 말씀드렸던 'VoTT가 내부 메모리에 자체적으로 provider registry를 운용'하는 부분입니다. 보다 정확히는 '클라이언트 내부 메모리'에 정보를 저장합니다.

단적인 예로 같은 VoTT 연결 페이지 url을 다른 브라우저로만 접속하셔도 저장했었던 연결 정보가 보이지 않으실 겁니다.

참고로 해당 연결 정보는 VoTT 입장에서 'API를 통해 DB로 접근'할 수 있는 유일한 방법입니다.


저도 말씀주셨던 시나리오를 염두에 두고 초반부터 작업을 했으나 지금 말씀드린 '연결 정보의 로컬 저장'이라는 문제로 인해 오랜 시행착오 끝에 VoTT 시작 시 모든 작업자가 'API를 통해 DB로 접근하여' 동일한 정보를 가지는 것이 어렵다는 결론을 얻게 되었습니다.

따라서 상기 문제 및 이에 대해 앞에서 제안드린 세 가지 해결책은 여전히 유효하며, 다시 한번 세 번째 해결책을 설명드리면 관리자가 VoTT에서의 한 번의 연결 설정을 통해 'API를 통해 DB로 접근하여' 작업자들이 작업할 연결 및 task 설정을 해두고, 모든 작업자가 '설정된 연결 및 API를 통해 DB로 접근하여' 동일한 정보를 가지도록 하는 방법입니다.

**Comment by bongwon7** [comment]
네 결과물을 보지 않아서 100%확신은 서지 않지만 세번째 방법이 현재 판단하기에 가장 합당한 방법처럼 생각됩니다.

**Comment by bongwon7** [comment]
본안 관련하여 논의되었고 현실적으로 코드상에 URL을 수록하여 추가로 연결설정이 불필요하도록 해주시면 될것 같습니다.

따라서,

이전에 주셨던
> 관리자가 API �서버 등록, 프로젝트 생성을 직접 수행하여 다수의 Task 프로젝트 한 번에 생성, 사용자는 생성 없이 바로 작업 화면으로 이동 (관리 로드 - 사용자 링크 제공의 타협점으로 보입니다.)

이 부분은 수행하지 않으시는 걸로 이해하겠습니다. 일단은 시작버튼을 누르는 것으로 유지하겠습니다.

URL 설정 위치, 또는 방법 등을 안내해 주시면 테스트 서버 등에 반영해보겠습니다.
(혹시 Stella에서 태스크 생성 시 보내드리는 정보에 포함되어 있나요?)

**Comment by JinkiJung** [comment]
지난 회의에서 협의되었던 내용을 아래와 같이 구현하였습니다.

* 스텔라 서버 연결 설정을 src/assets/defaultConnection.json 으로 저장하여 사용
* 어노테이션 작업 페이지 연결 시 해당 연결 설정을 통해 VoTT-dot project 파일을 불러옴 (보안 토큰 이슈 없이)

아래의 방법으로 이용하실 수 있습니다. (시작버튼을 누르는 단계가 없어졌습니다.)
1. Stella에서 $API/task/create?uuid=$UUID 를 통해 VoTT-dot project 파일 생성
2.  $VOTT_API/#/projects/$UUID/edit/$TYPE/$STATUS를 통해 VoTT-dot으로 접속

VoTT-dot의 0.1 브랜치에 반영하였습니다.
https://github.com/Digital-Maritime-Consultancy/VoTT-dot/pull/18

확인 및 테스트 후 이상이 없으면 이슈 종료를 부탁드립니다. 감사합니다.

**Comment by bongwon7** [comment]
우선은 이렇게 이해를 했습니다. (VoTT 환경설정은 되었다라는 전제입니다.)
1. Stella에서 $API/task/create?uuid=$UUID 에 로직대로 미리 정보 저장
`
{
"id":"8fabf525-b6fe-4ffb-a311-d1b1601b94fe",
"name":"8fabf525-b6fe-4ffb-a311-d1b1601b94fe",
"sourceConnection":{
"name":"source",
"providerType":"remoteStorage",
"providerOptions":{
"url":"http://localhost:8081/data/image",
"taskId":"8fabf525-b6fe-4ffb-a311-d1b1601b94fe",
"taskServerUrl":"http://localhost:8081/rest/task"
}
},
"targetConnection":{
"name":"target",
"providerType":"remoteStorage",
"providerOptions":{
"url":"http://localhost:8081/rest/file",
"taskId":"8fabf525-b6fe-4ffb-a311-d1b1601b94fe",
"taskServerUrl":"http://localhost:8081/rest/task"
}
},
"description":"Description",
"videoSettings":{
"frameExtractionRate":15
},
"dotToRectSettings":{
"url":"http://reco.kriso.synology.me"
},
"taskType":"Annotation",
"taskStatus":"In_progress",
"tags":[
{
"name":"asd",
"color":"#0549C2"
}
],
"version":"2.2.0",
"useSecurityToken":"false",
"securityToken":"8fabf525-b6fe-4ffb-a311-d1b1601b94fe Token",
"stellaUrl":"http://localhost:8081",
"assets":{
},
"activeLearningSettings":{
"autoDetect":false,
"predictTag":true,
"modelPathType":"coco"
},
"exportFormat":{
"providerType":"vottJson",
"providerOptions":{
"assetState":"visited",
"includeImages":true
}
}
}

`

2. $VOTT_API/#/projects/$UUID/edit/$TYPE/$STATUS를 통해 VoTT-dot으로 접속

그런데 화면과 같은 에러가 발생합니다. 제가 무엇을 잘못했을까요?

사진에서 보면 저장된 task 정보는 불러 가는 것으로 확인됩니다.
 
![image](https://user-images.githubusercontent.com/56225430/159219392-c95c7332-a075-4bec-a4b4-38d246a561ce.png)

**Comment by JinkiJung** [comment]
혹시 src/assets/defaultConnection.json도 공유해주실 수 있을까요?

**Comment by bongwon7** [comment]
여기있습니다.
{
    "id": "stella-connection",
    "name": "Stella",
    "description": "default connection configuration for VoTT-dot",
    "providerType": "remoteStorage",
    "providerOptions": {
        "url": "http://localhost:8081/rest/file",
        "taskId": "",
        "taskServerUrl": "http://localhost:8081/rest/task"
    }
}

**Comment by JinkiJung** [comment]
저장 시 토큰 관련 버그 수정되었습니다. 확인 부탁드립니다. :0)

https://github.com/Digital-Maritime-Consultancy/VoTT-dot/pull/20

**Comment by bongwon7** [comment]
확인해본 결과, 에러 결과가 달라졌습니다.
아마도 최초 로딩 전에 .vott 파일을 만든(file put) 후에 GET을 통해 로드해야 하는것과 관련있지 않나 싶습니다^^;
![image](https://user-images.githubusercontent.com/56225430/159262935-aa26bcd4-298d-4792-a903-05706f02a3d6.png)

**Comment by JinkiJung** [comment]
> 아마도 최초 로딩 전에 .vott 파일을 만든(file put) 후에 GET을 통해 로드해야 하는것과 관련있지 않나 싶습니다^^;

최초 로딩 전에 스텔라(/task/create)로부터 .vott 파일이 생성되어 있어야 합니다. 해당 오류는 .vott 파일이 없을 때만 발생됩니다.

**Comment by bongwon7** [comment]
최초에 STELLA에서 /task/create 로부터 생성하는 파일은 .vott가 없었는데 확장자를 추가하니
STELLA에서 생성하는 파일을 초기 프로젝트로 정상 인식되는 듯 합니다. 조금 더 테스트를 진행하고 본 이슈를 종결하겠습니다~

**Comment by JinkiJung** [comment]
[이 코드](https://github.com/Digital-Maritime-Consultancy/VoTT-dot-server/blob/stella-integration/src/main/java/org/dmc/vottdotserver/controllers/TaskController.java#L110)에 따르면 .vott 확장자가 있어야 하는데 이상하네요.

문제를 리포팅해주셔서 감사합니다. 덕분에 버그를 발견할 수 있었습니다. 테스트 중에 또 이슈가 발견되면 여기에 등록해주세요. 감사합니다.

**Comment by bongwon7** [comment]
.vott 확장자 없었던 것은 저희 STELLA시스템 예전에도 그랬는데 로딩이 되었고 
이후에 VoTT에서 .vott 파일을 생성 후 put 하는 절차로 갔기에 문제가 없었던것 같습니다.

혹시 현재도 /tast/create시 아래 정보가 필요한지만 알려주실 수 있으실까요?

	ts.setVottBackendUrl(stellaOrigin + "/rest/file");
	ts.setImageServerUrl(stellaOrigin + "/data/image");
	ts.setTaskServerUrl(stellaOrigin + "/rest/task");
	ts.setDotToRectUrl("http://reco.kriso.synology.me");

**Comment by bongwon7** [comment]
감사합니다~ 본 이슈를 종결하겠습니다.
