### ISSUE TITLE
/task get method with two different ways

### ISSUE THREAD

**Issue by bongwon7** [Digital-Maritime-Consultancy/VoTT-dot-server#7]
처음에 시스템을 로드하면 /task 호출에 대해서 다른 방법으로 호출합니다.

![image](https://user-images.githubusercontent.com/56225430/153804863-f2ee32f3-67c9-4725-b4e2-69580c6ed967.png)

![image](https://user-images.githubusercontent.com/56225430/153804893-8746cabf-59f5-49e1-81d6-7723f880e33b.png)

처음 로드할때는 아래 URL로 하시고
http://localhost:8081/rest/task?uuid=ecbc6794-e2b1-4787-bc1a-26ac40e1cdf5

이미지 asset에 대한 정보를 불러올땐 아래 URL로 하시는듯 합니다. 아마도 다음 호출은 GET이 아닌 PUT메소드 호출이 맞을 듯 싶습니다.
http://localhost:8081/rest/task/a4e7e5d8cd0b9ecdc87917d6d53abbe3--ecbc6794-e2b1-4787-bc1a-26ac40e1cdf5-asset.json%7D

**Comment by bongwon7** [comment]
GET을 의도하신 것인지.. 이부분은 바로 수정하지 마시고 조금더 검토한 후 진행하는 것이 좋겠습니다^^

**Comment by bongwon7** [comment]
/stella-integration/src/providers/storage/remoteStorage.ts

![image](https://user-images.githubusercontent.com/56225430/154199659-718478a7-df9a-4070-aae3-2d413b80b9e1.png)

여기 보시면 중괄호가 blobName 뒤에 두개 찍혀있습니다.

동일 파일 내 아래 메소드에서도 같은 증상이 확인됩니다.

readText
writeText
deleteFile
deleteContainer

**Comment by JinkiJung** [comment]
> /stella-integration/src/providers/storage/remoteStorage.ts
> 
> ![image](https://user-images.githubusercontent.com/56225430/154199659-718478a7-df9a-4070-aae3-2d413b80b9e1.png)
> 
> 여기 보시면 중괄호가 blobName 뒤에 두개 찍혀있습니다.
> 
> 동일 파일 내 아래 메소드에서도 같은 증상이 확인됩니다.
> 
> readText writeText deleteFile deleteContainer

상기 버그 아래와 같이 수정되었습니다.
https://github.com/Digital-Maritime-Consultancy/VoTT-dot/pull/9/commits/6aa6a1bf808f7142d2099e6621f08a40abc36384

**Comment by JinkiJung** [comment]
> 처음에 시스템을 로드하면 /task 호출에 대해서 다른 방법으로 호출합니다.
> 
> ![image](https://user-images.githubusercontent.com/56225430/153804863-f2ee32f3-67c9-4725-b4e2-69580c6ed967.png)
> 
> ![image](https://user-images.githubusercontent.com/56225430/153804893-8746cabf-59f5-49e1-81d6-7723f880e33b.png)
> 
> 처음 로드할때는 아래 URL로 하시고 http://localhost:8081/rest/task?uuid=ecbc6794-e2b1-4787-bc1a-26ac40e1cdf5
> 
> 이미지 asset에 대한 정보를 불러올땐 아래 URL로 하시는듯 합니다. 아마도 다음 호출은 GET이 아닌 PUT메소드 호출이 맞을 듯 싶습니다. http://localhost:8081/rest/task/a4e7e5d8cd0b9ecdc87917d6d53abbe3--ecbc6794-e2b1-4787-bc1a-26ac40e1cdf5-asset.json%7D

이미지 어셋데이터의 URL은 task 데이터의 "vottBackendUrl"의 값을 사용합니다. 따라서 사용 중이신 환경에서 해당 값이 "http://localhost:8081/rest/task"로 설정되어 있는지 확인이 먼저 필요합니다.
더불어 왜 호출이 GET이 아닌 PUT이 필요한지 보다 구체적으로 이유를 들어볼 수 있을까요?

**Comment by bongwon7** [comment]
GET-PUT 필요 여부보다는, 두 메소드 간에 parameter로 하는 부분과 pathvariable로 다르다는 부분 말씀드리고 싶었습니다^^

**Comment by JinkiJung** [comment]
맞습니다. 저 개인적으로는 모두 path variable로 통일하고 싶었으나 task 관련 API는 정봉원 책임님과 상의가 필요할 것 같아 일단 두었습니다. task 조회에 대한 '/all' 구현도 마찬가지이며 query parameter를 사용해야 한다면 모든 task를 조회하는 API는 아예 삭제하고자 합니다. 조회 시 query parameter 값은 해당 GET 호출의 필수값이기 때문입니다.

**Comment by bongwon7** [comment]
어느편이 프로세스가 좀 깔끔해질까요? 저는 어느편이라도 괜찮을거 같은데요.
task를 조회하는 API를 삭제하겠다 하심은 향후에
{StellaUrl}?taskId?=${uuid} 이런 방식을 취하고자 하심이 맞으실지요?

현재 VoTT-dot-server에 있는 API대로 하면 404 에러가 발생합니다.
![image](https://user-images.githubusercontent.com/56225430/155125699-6536c89b-74a7-41ee-950e-52f3a5649acc.png)

**Comment by JinkiJung** [comment]
* 함수1: 모든 task 목록 리턴
` @GetMapping(value = "")
    public ResponseEntity<List<Task>> getAllTasks() {
        ...
    }`
* 함수2: 특정 task 리턴
`
    @GetMapping(value = "", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<TaskDto> getTask(@RequestParam("uuid") String id) throws DataNotFoundException{
        ...
    }`

* 목표: GET을 통해 모든 task를 불러오기
query parameter를 사용하는 현재 버전에서 함수1에서 '/all' 경로를 제외시킨 위의 코드를 실행하고 query parameter를 의도적으로 주지 않고 GET API를 호출하면 getAllTasks() 함수가 호출되지 않고 getTask만 호출됩니다.

결국 task의 목록을 리턴하는 getAllTasks 함수를 호출하기 위해선 경로를 다르게 하거나 query parameter 외에 path variable을 사용해야 하는 것으로 보입니다.

혹시 다른 방법이 있을까요?

**Comment by JinkiJung** [comment]
> 현재 VoTT-dot-server에 있는 API대로 하면 404 에러가 발생합니다.

호출 API 이름 등 보다 구체적인 정보를 얻을 수 있을까요?

**Comment by bongwon7** [comment]
제가 추천드리고 싶은 방법은 

1) /task Get mapping 시 uuid가 null 일 경우 전체 목록을 리턴하고

2)  uuid가 있는 경우 특정 태스크를 반환하는 것입니다. 어떠실까요?

**Comment by JinkiJung** [comment]
> 제가 추천드리고 싶은 방법은
> 
> 1. /task Get mapping 시 uuid가 null 일 경우 전체 목록을 리턴하고
> 2. uuid가 있는 경우 특정 태스크를 반환하는 것입니다. 어떠실까요?

두 함수의 리턴 형식이 상이합니다.

**Comment by bongwon7** [comment]
첫번째 404
http://localhost:8081/rest/task/e841fed02bbfe1ef9b3e47cd92b16cdb--0b948128-c439-4996-bf46-a977cd753483-asset.json

두번째 404
http://localhost:8081/rest/task/0b948128-c439-4996-bf46-a977cd753483.vott

**Comment by bongwon7** [comment]
아 그러네요 리턴 형식이 상이하네요

**Comment by bongwon7** [comment]
일단 논점이 좀 흐려지는 듯하여 다시 정리드리면

VoTT 프로젝트 생성 '이후' 에 이미지를 로드할때 아래 두 요청이 동시에 일어납니다.

- http://localhost:8081**/rest/task?**uuid=ecbc6794-e2b1-4787-bc1a-26ac40e1cdf5
' TaskDto json 응답

- http://localhost:8081**/rest/task/**a4e7e5d8cd0b9ecdc87917d6d53abbe3--ecbc6794-e2b1-4787-bc1a-26ac40e1cdf5-asset.json%7D
' 저장된 VoTT 생성 파일들 응답

Stella 입장에서는 UUID로 검색을 하여 생성된 또는 저장된 JSON을 돌려드리는 동일한 동작을 하는데 
Query param / Path param 으로 URL을 두개를 요구한다는 것입니다^^

아울러. /file/ 호출은 더이상 사용하지 않는 것일지요? 아마도 두번째 호출은 VoTT-dot-server 에 있는 /file/ 호출과 더 가까워 보이네요

생각해보니 stella에서 보내드리는 URL에 따라 다르겠네요. 감안해서 어떤URL로 할지 다시 고민해보겠습니다

**Comment by bongwon7** [comment]
> 이미지 어셋데이터의 URL은 task 데이터의 "vottBackendUrl"의 값을 사용합니다. 따라서 사용 중이신 환경에서 해당 값이 "[http://localhost:8081/rest/task"로](http://localhost:8081/rest/task%22%EB%A1%9C) 설정되어 있는지 확인이 먼저 필요합니다.
> 더불어 왜 호출이 GET이 아닌 PUT이 필요한지 보다 구체적으로 이유를 들어볼 수 있을까요?

문제가 무엇인 줄 알았습니다. Stella server에서 task create 할때 잘못 설정하고 있었습니다.
task/create 시 제대로 rest/file로 해서 요청됨을 확인하였습니다.

본 이슈는 해소된 것으로 하겠습니다 감사합니다.

**Comment by JinkiJung** [comment]
감사합니다. 말씀주셨던 task-file 간 Query param / Path param의 불일치가 추후에도 문제가 될 것으로 예상하신다면 해당 주제로 회의를 가지는 것이 좋을 것 같습니다.
