### ISSUE TITLE
중간중간에 track 정보를 ms로 보내는듯합니다.

### ISSUE THREAD

**Issue by bongwon7** [Digital-Maritime-Consultancy/VoTT-dot-server#8]
![image](https://user-images.githubusercontent.com/56225430/155146344-01f779b7-0705-4b2e-8fa6-3b08f20398af.png)

별건 아니지만 저 추적정보가 안가게 할 수 없을까요?^^

**Comment by JinkiJung** [comment]
MS의 Application Insights 로 인한 tracing 이었고 해당 부분을 제거하였습니다.
https://github.com/Digital-Maritime-Consultancy/VoTT-dot/pull/10/commits/52f7292e43ce333426712151fdd3f458f10f8e00
