### ISSUE TITLE
X 버튼과 V버튼 모두 asset에 대한 .json이 저장되어야 합니다.

### ISSUE THREAD

**Issue by bongwon7** [Digital-Maritime-Consultancy/VoTT-dot-server#9]
![image](https://user-images.githubusercontent.com/56225430/155148068-40e821db-c5cb-4ef7-80fd-616582cc1a04.png)

메일에도 남겨드렸지만 일원화된 관리를 위해 여기 이슈 남겨드립니다.

상기 제목과 같이 X버튼과 V버튼 모두 .json이 저장되어야 하는데

현재 V버튼에 대한 저장이 되지 않습니다.

**Comment by JinkiJung** [comment]
해당 부분 수정되었습니다. 확인해보시고 문제 없으면 이슈 종료를 부탁드립니다.
https://github.com/Digital-Maritime-Consultancy/VoTT-dot/pull/10/commits/c772aada46906497e109afa9dac8658a28d22bf0

**Comment by bongwon7** [comment]
정상기능 확인했습니다. 이슈를 종료합니다^^
